"""updated the door lock table

Revision ID: 201f7c03a8d4
Revises: ab4ab0a11c7c
Create Date: 2025-12-17 03:32:20.180731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '201f7c03a8d4'
down_revision = 'ab4ab0a11c7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('door_lock', schema=None) as batch_op:
        batch_op.add_column(sa.Column('device_id', sa.UUID(), nullable=False))
        batch_op.alter_column('user_id',
               existing_type=sa.UUID(),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('door_lock_user_id_key'), type_='unique')
        batch_op.create_unique_constraint(None, ['device_id'])
        batch_op.create_foreign_key(None, 'device', ['device_id'], ['id'])

    with op.batch_alter_table('face_image', schema=None) as batch_op:
        batch_op.add_column(sa.Column('supabase_path', sa.String(length=500), nullable=True))
        batch_op.alter_column('path',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=500),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('face_image', schema=None) as batch_op:
        batch_op.alter_column('path',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.drop_column('supabase_path')

    with op.batch_alter_table('door_lock', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint(batch_op.f('door_lock_user_id_key'), ['user_id'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('user_id',
               existing_type=sa.UUID(),
               nullable=False)
        batch_op.drop_column('device_id')

    # ### end Alembic commands ###
